In [1]:
import pandas as pd
import numpy as np


In [2]:
salary = pd.read_csv(r'../Week-7-Project-Kaggle-Competition/salaries_data.csv',  index_col=False)
salary.head()

work_year experience_level employment_type        job_title  salary_in_usd  \
0       2022               SE              FT    Data Engineer         140250   
1       2022               SE              FT    Data Engineer         135000   
2       2021               MI              FT  BI Data Analyst         100000   
3       2021               MI              CT      ML Engineer         270000   
4       2021               MI              FT    Data Engineer          26005   

  employee_residence  remote_ratio company_location company_size  
0                 US           100               US            M  
1                 US           100               US            M  
2                 US           100               US            M  
3                 US           100               US            L  
4                 RO             0               US            L

In [3]:
salary.shape

(500, 9)

In [4]:
test = pd.read_csv(r'../Week-7-Project-Kaggle-Competition/test.csv', index_col=False)
test.head()

work_year experience_level employment_type                   job_title  \
0       2020               SE              FT  Machine Learning Scientist   
1       2020               MI              FT           Lead Data Analyst   
2       2020               MI              FT                Data Analyst   
3       2020               MI              FT   Machine Learning Engineer   
4       2020               MI              FT        Product Data Analyst   

  employee_residence  remote_ratio company_location company_size  
0                 JP             0               JP            S  
1                 US           100               US            L  
2                 US           100               US            L  
3                 CN             0               CN            M  
4                 IN           100               IN            L

In [5]:
salary.shape

(500, 9)

In [6]:
sample = pd.read_csv(r'../Week-7-Project-Kaggle-Competition/sample.csv',  index_col=False)
sample.head()
sample.shape

(107, 2)

In [7]:
top = pd.concat([salary, test], axis=0)

top.shape


(607, 9)

In [8]:
top.head()

work_year experience_level employment_type        job_title  salary_in_usd  \
0       2022               SE              FT    Data Engineer       140250.0   
1       2022               SE              FT    Data Engineer       135000.0   
2       2021               MI              FT  BI Data Analyst       100000.0   
3       2021               MI              CT      ML Engineer       270000.0   
4       2021               MI              FT    Data Engineer        26005.0   

  employee_residence  remote_ratio company_location company_size  
0                 US           100               US            M  
1                 US           100               US            M  
2                 US           100               US            M  
3                 US           100               US            L  
4                 RO             0               US            L

In [9]:
top.describe().T

count           mean           std     min      25%       50%  \
work_year      607.0    2021.405272      0.692133  2020.0   2021.0    2022.0   
salary_in_usd  500.0  112996.216000  69613.750601  2859.0  64594.5  103080.0   
remote_ratio   607.0      70.922570     40.709130     0.0     50.0     100.0   

                    75%       max  
work_year        2022.0    2022.0  
salary_in_usd  150000.0  450000.0  
remote_ratio      100.0     100.0

In [10]:
corr = top.corr()
corr

work_year  salary_in_usd  remote_ratio
work_year       1.000000       0.170159      0.076314
salary_in_usd   0.170159       1.000000      0.146204
remote_ratio    0.076314       0.146204      1.000000

In [11]:
top.experience_level.value_counts()


SE    280
MI    213
EN     88
EX     26
Name: experience_level, dtype: int64

In [12]:
top.company_location.value_counts()

US    355
GB     47
CA     30
DE     28
IN     24
FR     15
ES     14
GR     11
JP      6
PT      4
AT      4
PL      4
NL      4
PK      3
DK      3
AU      3
BR      3
AE      3
TR      3
LU      3
MX      3
CH      2
IT      2
CZ      2
RU      2
BE      2
SI      2
NG      2
CN      2
MT      1
HN      1
IL      1
RO      1
SG      1
CO      1
IQ      1
HR      1
NZ      1
HU      1
IR      1
DZ      1
EE      1
UA      1
CL      1
KE      1
VN      1
IE      1
AS      1
MD      1
MY      1
Name: company_location, dtype: int64

In [13]:
top10 = list(top.company_location.value_counts().head(9).index)
top.loc[-top['company_location'].isin(top10), ['company_location']] = 'OTHER'


In [14]:
top.company_location.value_counts()

US       355
OTHER     77
GB        47
CA        30
DE        28
IN        24
FR        15
ES        14
GR        11
JP         6
Name: company_location, dtype: int64

In [15]:
top.employment_type.value_counts()

FT    588
PT     10
CT      5
FL      4
Name: employment_type, dtype: int64

In [16]:
top.work_year.value_counts()

2022    318
2021    217
2020     72
Name: work_year, dtype: int64

In [17]:
top.job_title.value_counts()


Data Scientist                              143
Data Engineer                               132
Data Analyst                                 97
Machine Learning Engineer                    41
Research Scientist                           16
Data Science Manager                         12
Data Architect                               11
Big Data Engineer                             8
Machine Learning Scientist                    8
Director of Data Science                      7
AI Scientist                                  7
Data Analytics Manager                        7
Principal Data Scientist                      7
Data Science Consultant                       7
Computer Vision Engineer                      6
Lead Data Engineer                            6
BI Data Analyst                               6
ML Engineer                                   6
Data Engineering Manager                      5
Business Data Analyst                         5
Applied Data Scientist                  

In [18]:
top.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary_in_usd', 'employee_residence', 'remote_ratio',
       'company_location', 'company_size'],
      dtype='object')

 ## DUMMIES --

In [19]:


from sklearn.preprocessing import StandardScaler, MinMaxScaler  # normalizacion

from sklearn.decomposition import PCA    # PCA

import warnings
warnings.simplefilter('ignore')

In [20]:
top.salary_in_usd.max() 


450000.0

In [21]:
top['salary_in_usd'] = top['salary_in_usd'].replace([450000],103080)


In [22]:
# top.salary_in_usd.median()

In [23]:
#top['salary_in_usd'] = top['salary_in_usd'].replace([423000],103080)


In [24]:
#top['salary_in_usd'] = top['salary_in_usd'].replace([416000],103080)


In [25]:
#top['salary_in_usd'].values[top['salary_in_usd'] > 412000 ] = 1103080

In [26]:
top.salary_in_usd.max()

423000.0

In [27]:


data= top.drop(['employee_residence', 'remote_ratio', 'job_title'], axis = 1 )

data=pd.get_dummies(data)
data


work_year  salary_in_usd  experience_level_EN  experience_level_EX  \
0         2022       140250.0                    0                    0   
1         2022       135000.0                    0                    0   
2         2021       100000.0                    0                    0   
3         2021       270000.0                    0                    0   
4         2021        26005.0                    0                    0   
..         ...            ...                  ...                  ...   
102       2022            NaN                    0                    0   
103       2022            NaN                    0                    0   
104       2022            NaN                    0                    0   
105       2022            NaN                    1                    0   
106       2022            NaN                    0                    0   

     experience_level_MI  experience_level_SE  employment_type_CT  \
0                      0                    1                   0   
1                      0                    1                   0   
2                      1                    0                   0   
3                      1                    0                   1   
4                      1                    0                   0   
..                   ...                  ...                 ...   
102                    0                    1                   0   
103                    0                    1                   0   
104                    0                    1                   0   
105                    0                    0                   0   
106                    0                    1                   0   

     employment_type_FL  employment_type_FT  employment_type_PT  ...  \
0                     0                   1                   0  ...   
1                     0                   1                   0  ...   
2                     0                   1                   0  ...   
3                     0                   0                   0  ...   
4                     0                   1                   0  ...   
..                  ...                 ...                 ...  ...   
102                   0                   1                   0  ...   
103                   0                   1                   0  ...   
104                   0                   1                   0  ...   
105                   0                   1                   0  ...   
106                   0                   1                   0  ...   

     company_location_FR  company_location_GB  company_location_GR  \
0                      0                    0                    0   
1                      0                    0                    0   
2                      0                    0                    0   
3                      0                    0                    0   
4                      0                    0                    0   
..                   ...                  ...                  ...   
102                    0                    0                    0   
103                    0                    0                    0   
104                    0                    0                    0   
105                    0                    0                    0   
106                    0                    0                    0   

     company_location_IN  company_location_JP  company_location_OTHER  \
0                      0                    0                       0   
1                      0                    0                       0   
2                      0                    0                       0   
3                      0                    0                       0   
4                      0                    0                       0   
..                   ...                  ...                     ...   
102                    0                    0             

## SEPARAMOS EXCELS

In [28]:
salary_lim= data.iloc[:500,:]
salary_lim

work_year  salary_in_usd  experience_level_EN  experience_level_EX  \
0         2022       140250.0                    0                    0   
1         2022       135000.0                    0                    0   
2         2021       100000.0                    0                    0   
3         2021       270000.0                    0                    0   
4         2021        26005.0                    0                    0   
..         ...            ...                  ...                  ...   
495       2022       100000.0                    0                    0   
496       2021         5882.0                    1                    0   
497       2022        90700.0                    0                    0   
498       2021        82528.0                    0                    0   
499       2021        70000.0                    1                    0   

     experience_level_MI  experience_level_SE  employment_type_CT  \
0                      0                    1                   0   
1                      0                    1                   0   
2                      1                    0                   0   
3                      1                    0                   1   
4                      1                    0                   0   
..                   ...                  ...                 ...   
495                    0                    1                   0   
496                    0                    0                   0   
497                    0                    1                   0   
498                    1                    0                   0   
499                    0                    0                   0   

     employment_type_FL  employment_type_FT  employment_type_PT  ...  \
0                     0                   1                   0  ...   
1                     0                   1                   0  ...   
2                     0                   1                   0  ...   
3                     0                   0                   0  ...   
4                     0                   1                   0  ...   
..                  ...                 ...                 ...  ...   
495                   0                   1                   0  ...   
496                   0                   1                   0  ...   
497                   0                   1                   0  ...   
498                   0                   1                   0  ...   
499                   0                   1                   0  ...   

     company_location_FR  company_location_GB  company_location_GR  \
0                      0                    0                    0   
1                      0                    0                    0   
2                      0                    0                    0   
3                      0                    0                    0   
4                      0                    0                    0   
..                   ...                  ...                  ...   
495                    0                    0                    0   
496                    0                    0                    0   
497                    0                    0                    0   
498                    0                    1                    0   
499                    0                    0                    0   

     company_location_IN  company_location_JP  company_location_OTHER  \
0                      0                    0                       0   
1                      0                    0                       0   
2                      0                    0                       0   
3                      0                    0                       0   
4                      0                    0                       0   
..                   ...                  ...                     ...   
495                    0                    0             

In [29]:
test_lim = data.iloc[500:,:].drop('salary_in_usd', axis = 1)
test_lim

work_year  experience_level_EN  experience_level_EX  experience_level_MI  \
0         2020                    0                    0                    0   
1         2020                    0                    0                    1   
2         2020                    0                    0                    1   
3         2020                    0                    0                    1   
4         2020                    0                    0                    1   
..         ...                  ...                  ...                  ...   
102       2022                    0                    0                    0   
103       2022                    0                    0                    0   
104       2022                    0                    0                    0   
105       2022                    1                    0                    0   
106       2022                    0                    0                    0   

     experience_level_SE  employment_type_CT  employment_type_FL  \
0                      1                   0                   0   
1                      0                   0                   0   
2                      0                   0                   0   
3                      0                   0                   0   
4                      0                   0                   0   
..                   ...                 ...                 ...   
102                    1                   0                   0   
103                    1                   0                   0   
104                    1                   0                   0   
105                    0                   0                   0   
106                    1                   0                   0   

     employment_type_FT  employment_type_PT  company_location_CA  ...  \
0                     1                   0                    0  ...   
1                     1                   0                    0  ...   
2                     1                   0                    0  ...   
3                     1                   0                    0  ...   
4                     1                   0                    0  ...   
..                  ...                 ...                  ...  ...   
102                   1                   0                    0  ...   
103                   1                   0                    0  ...   
104                   1                   0                    0  ...   
105                   1                   0                    1  ...   
106                   1                   0                    0  ...   

     company_location_FR  company_location_GB  company_location_GR  \
0                      0                    0                    0   
1                      0                    0                    0   
2                      0                    0                    0   
3                      0                    0                    0   
4                      0                    0                    0   
..                   ...                  ...                  ...   
102                    0                    0                    0   
103                    0                    0                    0   
104                    0                    0                    0   
105                    0                    0                    0   
106                    0                    0                    0   

     company_location_IN  company_location_JP  company_location_OTHER  \
0                      0                    1                       0   
1                      0                    0                       0   
2                      0                    0                       0   
3                      0                    0                       1   
4                      1                    0                       0   
..                   ...                  ...              

## standarizamos

In [30]:
#salary_lim=pd.DataFrame(StandardScaler().fit_transform(salary_lim._get_numeric_data()),
                      
                      #columns=salary_lim._get_numeric_data().columns)

salary_lim

work_year  salary_in_usd  experience_level_EN  experience_level_EX  \
0         2022       140250.0                    0                    0   
1         2022       135000.0                    0                    0   
2         2021       100000.0                    0                    0   
3         2021       270000.0                    0                    0   
4         2021        26005.0                    0                    0   
..         ...            ...                  ...                  ...   
495       2022       100000.0                    0                    0   
496       2021         5882.0                    1                    0   
497       2022        90700.0                    0                    0   
498       2021        82528.0                    0                    0   
499       2021        70000.0                    1                    0   

     experience_level_MI  experience_level_SE  employment_type_CT  \
0                      0                    1                   0   
1                      0                    1                   0   
2                      1                    0                   0   
3                      1                    0                   1   
4                      1                    0                   0   
..                   ...                  ...                 ...   
495                    0                    1                   0   
496                    0                    0                   0   
497                    0                    1                   0   
498                    1                    0                   0   
499                    0                    0                   0   

     employment_type_FL  employment_type_FT  employment_type_PT  ...  \
0                     0                   1                   0  ...   
1                     0                   1                   0  ...   
2                     0                   1                   0  ...   
3                     0                   0                   0  ...   
4                     0                   1                   0  ...   
..                  ...                 ...                 ...  ...   
495                   0                   1                   0  ...   
496                   0                   1                   0  ...   
497                   0                   1                   0  ...   
498                   0                   1                   0  ...   
499                   0                   1                   0  ...   

     company_location_FR  company_location_GB  company_location_GR  \
0                      0                    0                    0   
1                      0                    0                    0   
2                      0                    0                    0   
3                      0                    0                    0   
4                      0                    0                    0   
..                   ...                  ...                  ...   
495                    0                    0                    0   
496                    0                    0                    0   
497                    0                    0                    0   
498                    0                    1                    0   
499                    0                    0                    0   

     company_location_IN  company_location_JP  company_location_OTHER  \
0                      0                    0                       0   
1                      0                    0                       0   
2                      0                    0                       0   
3                      0                    0                       0   
4                      0                    0                       0   
..                   ...                  ...                     ...   
495                    0                    0             

------

In [31]:
#data=StandardScaler().fit_transform(data)


In [32]:
X=salary_lim.drop(['salary_in_usd'], axis=1)  # separacion X y

y=salary_lim.salary_in_usd

In [33]:
X.columns

Index(['work_year', 'experience_level_EN', 'experience_level_EX',
       'experience_level_MI', 'experience_level_SE', 'employment_type_CT',
       'employment_type_FL', 'employment_type_FT', 'employment_type_PT',
       'company_location_CA', 'company_location_DE', 'company_location_ES',
       'company_location_FR', 'company_location_GB', 'company_location_GR',
       'company_location_IN', 'company_location_JP', 'company_location_OTHER',
       'company_location_US', 'company_size_L', 'company_size_M',
       'company_size_S'],
      dtype='object')

In [66]:
X.shape

(500, 22)

---

## testing pred starts

In [35]:
from sklearn.linear_model import LinearRegression as LinReg
from sklearn.linear_model import Lasso        # regularizacion L1
from sklearn.linear_model import Ridge        # regularizacion L2
from sklearn.linear_model import ElasticNet   # regularizacion L1+L2


# se inician los modelos
linreg=LinReg()
lasso=Lasso()
ridge=Ridge()
elastic=ElasticNet()

In [36]:
from sklearn.ensemble import GradientBoostingRegressor as GBR

from xgboost import XGBRegressor as XGBR

from catboost import CatBoostRegressor as CTR
from sklearn.svm import SVR  # support vector regressor
from sklearn.ensemble import GradientBoostingRegressor as GBR

svr=SVR()

gbr=GBR()
xgbr=XGBR()
ctr=CTR()



In [37]:
#!pip install xgboost
#!pip install catboost
#!pip install lightgbm

In [38]:
from sklearn.model_selection import train_test_split as tts # el alias es cosa mia

X_train, X_test, y_train, y_test = tts(X, y, train_size=0.8, test_size=0.2, random_state=22)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((400, 22), (100, 22), (400,), (100,))

In [39]:
from sklearn.ensemble import RandomForestRegressor as RFR  
from sklearn.tree import ExtraTreeRegressor as ETR

rfr=RFR()
etr=ETR()

In [40]:
linreg.fit(X_train, y_train)
lasso.fit(X_train, y_train)
ridge.fit(X_train, y_train)
elastic.fit(X_train, y_train)
svr.fit(X_train, y_train)
rfr.fit(X_train, y_train)
etr.fit(X_train, y_train)
gbr.fit(X_train, y_train)
xgbr.fit(X_train, y_train)
ctr.fit(X_train, y_train, verbose=0)




In [41]:
linreg.predict(X_test)[:10]



array([140288., 144384., 144384.,  32768., 144384., 169984., 115712.,
        50176.,  11264.,  74752.])

In [42]:
lasso.predict(X_test)[:10]


array([137291.28950103, 148482.19299953, 148482.19299953,  38936.80385924,
       148482.19299953, 167552.64704326, 118220.83545731,  53914.12796927,
        27421.32845077,  74502.44032652])

In [43]:
ridge.predict(X_test)[:10]

array([136721.94443071, 148521.12568214, 148521.12568214,  40588.81067811,
       148521.12568214, 167302.60128217, 117940.46883068,  54414.57635408,
        27812.70807769,  73944.82007534])

In [44]:
elastic.predict(X_test)[:10]


array([115293.69253522, 134676.9704538 , 134676.9704538 ,  86035.6070417 ,
       134676.9704538 , 134515.96516121, 115454.69782781,  92622.61351894,
        80633.27595388,  92316.8838605 ])

In [45]:
svr.predict(X_test)[:10]


array([103425.49999632, 103425.50011531, 103425.50011531, 103425.49994606,
       103425.50011531, 103425.5000712 , 103425.50004043, 103425.49997786,
       103425.49994093, 103425.49997632])

In [46]:
rfr.predict(X_test)[:10]


array([130839.79592389, 142513.6964356 , 142513.6964356 ,  47355.68010317,
       142513.6964356 , 174833.54314695, 141555.01896373,  68318.43273413,
        40888.83064286,  76369.99131612])

In [47]:
etr.predict(X_test)[:10]


array([131623.0952381 , 142482.24271845, 142482.24271845,  38776.        ,
       142482.24271845, 172193.375     , 142739.93333333,  58621.        ,
        48351.5       ,  76009.30769231])

In [48]:
gbr.predict(X_test)[:10]


array([129726.51425372, 144520.59243935, 144520.59243935,  52170.01237302,
       144520.59243935, 177584.41300488, 129146.04517963,  72616.54820149,
        35670.68707682,  78178.48457078])

In [49]:
xgbr.predict(X_test)[:10]


array([131437.22 , 142491.31 , 142491.31 ,  44158.902, 142491.31 ,
       172457.31 , 142724.31 ,  70247.55 ,  44147.94 ,  76019.98 ],
      dtype=float32)

In [50]:
ctr.predict(X_test)[:10]


array([130790.5795699 , 142764.23038291, 142764.23038291,  41835.98403367,
       142764.23038291, 174106.79133185, 140864.20098176,  83212.20170077,
        28925.88769602,  76338.83160973])

predict

In [51]:
from sklearn.metrics import mean_squared_error as mse  # error cuadratico medio


In [52]:
# regresion lineal

y_pred=linreg.predict(X_test)

mse(y_test, y_pred, squared=False)

40652.93058710528

In [53]:
# lasso

#y_pred=lasso.predict(X_test)

#mse(y_test, y_pred, squared=False) 

41124.557351389514

In [54]:
# ridge

#y_pred=ridge.predict(X_test)

#mse(y_test, y_pred, squared=False)

40803.133933128505

In [55]:
#elastic

#y_pred=elastic.predict(X_test)

#mse(y_test, y_pred, squared=False)

47124.95194627478

In [56]:
#rfr

 
#y_pred=rfr.predict(X_test)
#mse(y_test, y_pred, squared=False)  # RMSE

43307.62957070108

In [57]:
# etr

#y_pred=etr.predict(X_test)

#mse(y_test, y_pred, squared=False)  # RMSE

50222.14181089197

In [58]:
# svr

#y_pred=svr.predict(X_test)

#mse(y_test, y_pred, squared=False)  # RMSE

56469.46316711276

In [59]:
# boosting

#y_pred=xgbr.predict(X_test)
#mse(y_test, y_pred, squared=False)  # RMSE

45195.837292520744

In [60]:
#y_pred=ctr.predict(X_test)

#mse(y_test, y_pred, squared=False)  # RMSE

43648.97796228773

In [67]:
#y_pred=linreg.predict(test_lim)


#y_pred

array([ 89088., 133120., 133120.,  22528.,  30720.,  55296., 162816.,
        68608., 106496., 162816.,   9216., 162816., 102400., -16384.,
        55296.,  40960., 134144., 140288.,  60416., 112640., 140288.,
       100352.,  82944., 138240.,  -7168.,  15360.,  96256., 169984.,
        28672., 146432., 114688., 123904., 121856.,  65536.,  11264.,
        28672., 138240.,  32768.,  56320., 169984.,  -9216.,  20480.,
       140288., 169984.,  96256., 225280., 108544.,  56320., 123904.,
        60416., 123904.,  60416., 115712., 115712., 115712.,  74752.,
       144384., 200704., 144384., 144384., 144384., 200704., 144384.,
       144384., 144384., 144384., 144384., 144384., 144384.,  74752.,
       115712., 176128., 119808.,  52224.,  96256., 115712.,  38912.,
        74752.,  98304., 146432.,  12288.,  44032., 130048., 176128.,
       115712.,  74752.,  74752., 144384., 144384.,  96256.,  62464.,
        67584., 110592.,  50176., 144384., 130048.,  22528.,  58368.,
        58368., 1443

In [68]:
#index_lst = [i for i in range(107)]
#results_jaime = pd.DataFrame({"id" : index_lst, "salary_in_usd" : y_pred})
#results_jaime.to_csv("results_jaime.csv", index=False)

In [61]:
#pip install h2o

In [62]:
import h2o

from h2o.automl import H2OAutoML

In [63]:
train=X
test=y

In [64]:
#h2o.init()